-- MySQL Script generated by MySQL Workbench
-- Sun Apr 10 12:33:02 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_contato
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_contato
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_contato` DEFAULT CHARACTER SET utf8 ;
USE `bd_contato` ;

-- -----------------------------------------------------
-- Table `bd_contato`.`Contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_contato`.`Contato` (
  `id_Contato` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Contato`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
